"""
verify_action_impact — ARQ task.
Runs 7 days after seller marks action as done.
Compares the SPECIFIC metric targeted by the action's rule, not global net_revenue.

FIX HIGH-2: Previous implementation compared global net_revenue delta across two
snapshots. This attributes ALL revenue improvement to one action, even when multiple
actions are pending or when improvement stems from unrelated factors. This leads to:
  1. Over-attribution: inflated confirmed_delta
  2. Double-counting: 2 actions in same week each claim full delta → sum > reality
Both destroy trust in the Weekly Receipt when sellers notice the numbers don't add up.

Fix: each rule_id maps to a specific metric to check in top_skus_json or
top_creators_json, and compares THAT entity's metric before vs after.
"""
import uuid
from decimal import Decimal

import structlog
from sqlalchemy import select

from app.models.ai_action import AIAction
from app.models.insight_snapshot import InsightSnapshot

log = structlog.get_logger()

# Maps rule_id → (entity_type, metric_key) for metric-specific verification.
# Only rules listed here get metric-specific verification; others fall back to
# CONSERVATIVE mode (no confirmation, log warning) to avoid false attribution.
# F-1B-05: Removed phantom entries that were never generated by evaluate_rules():
#   - "creator_sample_no_content": evaluate_rules() never produces this rule_id
#   - "voucher_exceeds_margin": evaluate_rules() never produces this rule_id
#   (Add them here only when also added to action_rules.py evaluate_rules())
RULE_METRIC_MAP: dict[str, tuple[str, str]] = {
    "sku_margin_negative":   ("sku",     "margin_pct"),
    "sku_refund_spike":      ("sku",     "refund_rate"),
    "creator_roi_below_one": ("creator", "revenue_efficiency"),
    # Planned but not yet implemented in evaluate_rules() — add both places together:
    # "voucher_exceeds_margin":    ("sku",     "margin_pct"),
    # "creator_sample_no_content": ("creator", "sample_conversion_rate"),
}


def _extract_entity_metric(
    snapshot_json_field: list,
    entity_id: str,
    metric_key: str,
) -> Decimal | None:
    """Extract a specific metric for a specific entity from a JSON snapshot field."""
    for item in snapshot_json_field:
        if str(item.get("sku_id") or item.get("creator_id") or item.get("id", "")) == entity_id:
            raw = item.get(metric_key)
            if raw is not None:
                try:
                    return Decimal(str(raw))
                except Exception:
                    return None
    return None


async def verify_action_impact(ctx: dict, action_id: str) -> None:
    """
    Compare the SPECIFIC metric before/after for the entity targeted by this action.
    Only confirm impact if THAT entity's relevant metric improved.
    """
    AsyncSessionLocal = ctx["db_session_factory"]  # noqa: N806

    async with AsyncSessionLocal() as db:
        action = await db.scalar(
            select(AIAction).where(AIAction.id == uuid.UUID(action_id))
        )
        if not action or action.status != "done":
            return

        baseline_snapshot = await db.scalar(
            select(InsightSnapshot).where(
                InsightSnapshot.id == action.insight_snapshot_id
            )
        )
        if not baseline_snapshot:
            log.warning("verify_impact.no_baseline", action_id=action_id)
            return

        latest_snapshot = await db.scalar(
            select(InsightSnapshot)
            .where(InsightSnapshot.shop_id == action.shop_id)
            .order_by(InsightSnapshot.created_at.desc())
            .limit(1)
        )
        if not latest_snapshot or latest_snapshot.id == baseline_snapshot.id:
            log.info("verify_impact.no_new_data", action_id=action_id)
            return

        # ── Metric-specific verification ──────────────────────────────────────
        rule_id = action.rule_trigger  # e.g. "sku_margin_negative"
        if rule_id not in RULE_METRIC_MAP:
            log.warning(
                "verify_impact.unknown_rule_no_confirmation",
                action_id=action_id,
                rule_id=rule_id,
            )
            return

        entity_type, metric_key = RULE_METRIC_MAP[rule_id]

        # Determine which JSON field to look in
        if entity_type == "sku":
            baseline_list = baseline_snapshot.top_skus_json or []
            latest_list = latest_snapshot.top_skus_json or []
        elif entity_type == "creator":
            baseline_list = baseline_snapshot.top_creators_json or []
            latest_list = latest_snapshot.top_creators_json or []
        else:
            log.warning("verify_impact.unknown_entity_type", entity_type=entity_type)
            return

        # Extract entity_id from action's rule trigger metadata
        # action.rule_trigger stores the rule_id; entity_id comes from action_triggers_json
        # We locate it by matching action_type and finding the trigger entity
        entity_id = _resolve_entity_id(action, baseline_snapshot)
        if not entity_id:
            log.warning("verify_impact.entity_id_not_found", action_id=action_id)
            return

        baseline_val = _extract_entity_metric(baseline_list, entity_id, metric_key)
        latest_val   = _extract_entity_metric(latest_list,   entity_id, metric_key)

        if baseline_val is None or latest_val is None:
            log.info(
                "verify_impact.metric_not_found_in_snapshot",
                action_id=action_id,
                entity_id=entity_id,
                metric_key=metric_key,
            )
            return

        # For margin/roi: higher is better. For refund_rate: lower is better.
        lower_is_better = metric_key in ("refund_rate",)
        if lower_is_better:
            improved = latest_val < baseline_val
            delta_magnitude = baseline_val - latest_val
        else:
            improved = latest_val > baseline_val
            delta_magnitude = latest_val - baseline_val

        if improved:
            # Attribute improvement conservatively: only the entity's metric delta,
            # NOT the entire shop's net_revenue swing
            action.confirmed_delta = delta_magnitude
            action.is_confirmed_impact = True
            action.actual_impact_json = {
                "entity_type": entity_type,
                "entity_id": entity_id,
                "metric_key": metric_key,
                "baseline_value": str(baseline_val),
                "latest_value": str(latest_val),
                "delta": str(delta_magnitude),
                "baseline_snapshot_id": str(baseline_snapshot.id),
                "latest_snapshot_id": str(latest_snapshot.id),
                "attribution_method": "metric_specific",  # audit trail
            }
            await db.flush()
            log.info(
                "verify_impact.confirmed",
                action_id=action_id,
                entity_id=entity_id,
                metric_key=metric_key,
                delta=str(delta_magnitude),
            )
        else:
            log.info(
                "verify_impact.no_improvement",
                action_id=action_id,
                entity_id=entity_id,
                metric_key=metric_key,
                baseline=str(baseline_val),
                latest=str(latest_val),
            )


def _resolve_entity_id(action: AIAction, snapshot: InsightSnapshot) -> str | None:
    """Extract entity_id for THIS specific action.

    FIX v0.5.2: previously used first-match-by-rule-id from action_triggers_json.
    If shop has 3 SKUs with sku_margin_negative, all 3 actions resolved to the
    same (first) entity → metric verification ran against wrong SKU →
    confirmed_delta attributed incorrectly → Weekly Receipt numbers wrong.

    process_import.py (v0.4+) stores entity_id in action.source_insight_json["entity"]
    at action creation time. We use that directly. Fall back to first-match for
    legacy actions created before v0.4 fix landed.
    """
    # Primary path (v0.4+): entity stored on the action itself
    src = action.source_insight_json or {}
    entity_id = src.get("entity")
    if entity_id:
        return str(entity_id)
    # Legacy fallback for pre-v0.4 actions — first match by rule_id
    triggers = snapshot.action_triggers_json or []
    for trigger in triggers:
        if trigger.get("rule_id") == action.rule_trigger:
            return str(trigger.get("entity_id", ""))
    return None
